on:
  release:
    types: [ published ]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@24d166886aee4646d448c8a389ff9e1ebcab3682
        with:
          webhook_url: ${{ secrets.DISCORD }}
          color: "2105893"
          username: "Commentable"
          avatar_url: "https://avatars.githubusercontent.com/u/116525492?s=96&v=4"
          content: "||@everyone||"
          footer_title: "Commentable"
          footer_icon_url: "https://avatars.githubusercontent.com/u/116525492?s=96&v=4"
          footer_timestamp: true
